enum Module {
  USERS = 'USERS',
  ROLES = 'ROLES',
  CUSTOMERS = 'CUSTOMERS',
  COMPANIES = 'COMPANIES',
  PROVIDERS = 'PROVIDERS',
  PRODUCTS = 'PRODUCTS',
  CATEGORIES = 'CATEGORIES'
}

export default Module
